import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BodyLayout from "./layout/body-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skill Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow:wght@400;700&display=swap" rel="stylesheet" />
      </head>

      <body className={inter.className}>
        <BodyLayout>
          {children}
        </BodyLayout>
      </body>
    </html>
  );
}
